#include "common_token.h"
#include "error.h"

const char *punctuator_str(int x) {
  switch ((enum Punctuator)x) {
  case LEFT_BRACKET:
    return "LEFT_BRACKET";
  case RIGHT_BRACKET:
    return "RIGHT_BRACKET";
  case LEFT_PAREN:
    return "LEFT_PAREN";
  case RIGHT_PAREN:
    return "RIGHT_PAREN";
  case LEFT_BRACE:
    return "LEFT_BRACE";
  case RIGHT_BRACE:
    return "RIGHT_BRACE";
  case DOT:
    return "DOT";
  case ARROW:
    return "ARROW";
  case INCREMENT:
    return "INCREMENT";
  case DECREMENT:
    return "DECREMENT";
  case AMPASAND:
    return "AMPASAND";
  case ASTERISK:
    return "ASTERISK";
  case PLUS:
    return "PLUS";
  case MINUS:
    return "MINUS";
  case NEGATE:
    return "NEGATE";
  case EXCLAMATION:
    return "EXCLAMATION";
  case DIVIDE:
    return "DIVIDE";
  case REMIND:
    return "REMIND";
  case LEFT_SHIFT:
    return "LEFT_SHIFT";
  case RIGHT_SHIFT:
    return "RIGHT_SHIFT";
  case LESS_THAN:
    return "LESS_THAN";
  case GREATER_THAN:
    return "GREATER_THAN";
  case LESS_EQUAL:
    return "LESS_EQUAL";
  case GREATER_EQUAL:
    return "GREATER_EQUAL";
  case EQUAL:
    return "EQUAL";
  case NOT_EQUAL:
    return "NOT_EQUAL";
  case EXCLUSIVE_OR:
    return "EXCLUSIVE_OR";
  case INCLUSIVE_OR:
    return "INCLUSIVE_OR";
  case LOGICAL_AND:
    return "LOGICAL_AND";
  case LOGICAL_OR:
    return "LOGICAL_OR";
  case QUESTION:
    return "QUESTION";
  case COLON:
    return "COLON";
  case SEMICOLON:
    return "SEMICOLON";
  case ELLIPSE:
    return "ELLIPSE";
  case ASSIGN:
    return "ASSIGN";
  case MULTIPLY_ASSIGN:
    return "MULTIPLY_ASSIGN";
  case DIVIDE_ASSIGN:
    return "DIVIDE_ASSIGN";
  case REMIND_ASSIGN:
    return "REMIND_ASSIGN";
  case ADD_ASSIGN:
    return "ADD_ASSIGN";
  case SUBTRACT_ASSIGN:
    return "SUBTRACT_ASSIGN";
  case LEFT_SHIFT_ASSIGN:
    return "LEFT_SHIFT_ASSIGN";
  case RIGHT_SHIFT_ASSIGN:
    return "RIGHT_SHIFT_ASSIGN";
  case AND_ASSIGN:
    return "AND_ASSIGN";
  case EXCLUSIVE_OR_ASSIGN:
    return "EXCLUSIVE_OR_ASSIGN";
  case INCLUSIVE_OR_ASSIGN:
    return "INCLUSIVE_OR_ASSIGN";
  case COMMA:
    return "COMMA";
  case SIGN:
    return "SIGN";
  case DOUBLE_SIGN:
    return "DOUBLE_SIGN";
  case DIGRAPH_LEFT_BRACKET:
    return "DIGRAPH_LEFT_BRACKET";
  case DIGRAPH_RIGHT_BRACKET:
    return "DIGRAPH_RIGHT_BRACKET";
  case DIGRAPH_LEFT_BRACE:
    return "DIGRAPH_LEFT_BRACE";
  case DIGRAPH_RIGHT_BRACE:
    return "DIGRAPH_RIGHT_BRACE";
  case DIGRAPH_SIGN:
    return "DIGRAPH_SIGN";
  case DIGRAPH_DOUBLE_SIGN:
    return "DIGRAPH_DOUBLE_SIGN";
  }
  ERROR("unknown enum variant: %d", x);
}

// vim: set ft=c ts=2 sw=2 et:
